/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames.Admin;
import Clases.Articulo;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author CRISTHIAN
 */
public class RegistrarProducto extends javax.swing.JFrame {

    String image;
    public RegistrarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lblTipo1 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        lblTalla = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        file = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(0, 0, 0));
        lblMarca.setText("Marca:");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 30));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 165, 210, -1));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo:");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 80, 30));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisas", "Pantalones", "Poleras", "Polos", "Zapatos", "Zapatillas" }));
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 125, 210, -1));

        lblTipo1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTipo1.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo1.setText("Género:");
        jPanel1.add(lblTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, 30));

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caballero", "Dama" }));
        jPanel1.add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 205, 210, -1));

        lblTalla.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTalla.setForeground(new java.awt.Color(0, 0, 0));
        lblTalla.setText("Talla:");
        jPanel1.add(lblTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 30));

        txtTalla.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 242, 70, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecio.setText("Precio:     S/");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 70, 30));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 242, 70, -1));

        lblImage.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblImage.setForeground(new java.awt.Color(0, 0, 0));
        lblImage.setText("Imagen:");
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 80, 30));

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 283, 70, -1));

        file.setText("...");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });
        jPanel1.add(file, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 323, -1, -1));
        jPanel1.add(txtFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 323, 180, -1));

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblStock.setForeground(new java.awt.Color(0, 0, 0));
        lblStock.setText("Stock:");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 80, 30));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.JPG", "jpg");
        fc.setFileFilter(filter);
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File selectedFile = fc.getSelectedFile();
            // Obtener la ruta del archivo
            String filePath = selectedFile.getAbsolutePath();
            txtFile.setText(filePath);
            String fileName = selectedFile.getName();
            // Copiar la imagen a una ubicación local
            String destinationPath = "src/images/productos"; // Especifica la ruta de destino donde quieres guardar la imagen
            File destinationFile = new File(destinationPath,fileName);
            try {
                java.nio.file.Files.copy(selectedFile.toPath(), destinationFile.toPath());
                image = destinationPath;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_fileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Articulo art = new Articulo();
       art.setMarca(txtMarca.getText());
       art.setTipo((String) cbTipo.getSelectedItem());
       art.setPrecio((float) Double.parseDouble(txtPrecio.getText()));
       art.setStock(Integer.parseInt(txtPrecio.getText()));
       art.setGenero((String) cbGenero.getSelectedItem());
       art.setTalla(txtTalla.getText());
       art.setImage(image);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c=evt.getKeyChar();

	if(Character.isLetter(c)) {
		getToolkit().beep();
		evt.consume();
	}  // TODO add your handling code he
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char c=evt.getKeyChar();
	if(Character.isLetter(c)) {
		getToolkit().beep();
		evt.consume();
	}  // TODO add your handling code he
    }//GEN-LAST:event_txtStockKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton file;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTalla;
    // End of variables declaration//GEN-END:variables
}
